### ISSUE TITLE
Error: Unable to parse color from string "#00000000" after adding plugin

### ISSUE THREAD

**Issue by willfarrell** [dfrankland/hyperterm-transparent-bg#11]
When I trigger a restart I get:
```bash
Uncaught Exception:
Error: Unable to parse color from string "#00000000"
    at Object.Color (/Applications/Hyper.app/Contents/Resources/app/node_modules/color/index.js:34:10)
    at Color (/Applications/Hyper.app/Contents/Resources/app/node_modules/color/index.js:11:10)
    at module.exports.bgColor (/Applications/Hyper.app/Contents/Resources/app/utils/to-electron-background-color.js:7:17)
    at Server.rpc.on (/Applications/Hyper.app/Contents/Resources/app/index.js:195:30)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.ipcListener (/Applications/Hyper.app/Contents/Resources/app/rpc.js:34:11)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
```

**Comment by lukemeaden** [comment]
Not a solution, but I came across the same issue. Using rgba worked for me (ie. `rgba(0,0,0,0.8)`)

**Comment by dfrankland** [comment]
After HyperTerm became Hyper.app, the way to set colors with transparency changed. Here's the commit where I updated the docs to reflect this: https://github.com/dfrankland/hyper-transparent-bg/commit/a7bc48575f391d5abe100fdb3f72cfe149a89526

**Comment by lukemeaden** [comment]
Thanks @dfrankland 
@willfarrell seems like that error is from Hyper itself, might be best to raise on their repo as the error message in `/Applications/Hyper.app/Contents/Resources/app/node_modules/color/index.js` might need updating

**Comment by willfarrell** [comment]
Oddly I had to make the change and then quit & open the app again to get rid of the error. Thanks for the feedback.
