### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by theskillwithin** [dfrankland/hyperterm-transparent-bg#6]
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Unable to parse color from string "#00000000"
    at Object.Color (/Applications/Hyper.app/Contents/Resources/app/node_modules/color/index.js:34:10)
    at Color (/Applications/Hyper.app/Contents/Resources/app/node_modules/color/index.js:11:10)
    at module.exports.bgColor (/Applications/Hyper.app/Contents/Resources/app/utils/to-electron-background-color.js:7:17)
    at createWindow (/Applications/Hyper.app/Contents/Resources/app/index.js:113:24)
    at click (/Applications/Hyper.app/Contents/Resources/app/menu.js:69:11)
    at MenuItem.click (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)

**Comment by dfrankland** [comment]
Ah, [Hyper.app is now using the `color` module](https://github.com/zeit/hyper/blob/master/app/utils/to-electron-background-color.js) which [doesn't support](https://github.com/Qix-/color/issues/72) [hex with alpha color strings](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba()).

**Comment by dfrankland** [comment]
All that that is needed is to change `#00000000` [here](https://github.com/dfrankland/hyperterm-transparent-bg/blob/master/index.js#L34) to be `rgba(0, 0, 0, 0)`.

**Comment by ieiayaobb** [comment]
@dfrankland How to fix this issue? waiting for a new official release?

**Comment by dfrankland** [comment]
@ieiayaobb To fix this issue, I believe all that we need to do is [make the change I listed above](https://github.com/dfrankland/hyperterm-transparent-bg/issues/6#issuecomment-262040940). Feel free to make a pull request 👍

**Comment by dfrankland** [comment]
This should be fixed with this commit: https://github.com/dfrankland/hyper-transparent-bg/commit/528ea32c4ef1d3cebbcc9d75a0ac0d402a76ae28

Also, please note that the package has been renamed from `hyperterm-transparent-bg` to `hyper-transparent-bg`.
