### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by prubini87** [dfrankland/hyperterm-transparent-bg#7]
I've tried several methods to get this to work on Windows 10 but apparently it can't. Here's the error I'm getting:

**Error while loading devtools extensions Error: Unable to parse color from string "#00000000"**

More details:

`C:\Users\prubi>
running in prod mode
electron will open file://C:\Users\prubi\AppData\Local\hyper\app-1.1.0\resources\app\index.html
**Error while loading devtools extensions Error: Unable to parse color from string "#00000000"**
    at Object.Color (C:\Users\prubi\AppData\Local\hyper\app-1.1.0\resources\app\node_modules\color\index.js:34:10)
    at Color (C:\Users\prubi\AppData\Local\hyper\app-1.1.0\resources\app\node_modules\color\index.js:11:10)
    at module.exports.bgColor (C:\Users\prubi\AppData\Local\hyper\app-1.1.0\resources\app\utils\to-electron-background-color.js:7:17)
    at createWindow (C:\Users\prubi\AppData\Local\hyper\app-1.1.0\resources\app\index.js:139:24)
    at installDevExtensions.then (C:\Users\prubi\AppData\Local\hyper\app-1.1.0\resources\app\index.js:357:3)`

Please look it up, I'd really like to have this functionality added to Hyper! ;D

**Comment by dfrankland** [comment]
Can you ensure that you are using `hyper-transparent-bg@1.5.2`? This was already fixed with this commit: https://github.com/dfrankland/hyper-transparent-bg/commit/528ea32c4ef1d3cebbcc9d75a0ac0d402a76ae28

**Comment by prubini87** [comment]
Thanks for your quick response!! I've ensured I have hyper-transparent-bg@1.5.2 and it's now working perfectly!! I'm afraid I was also trying to make hyperterm-transparent-bg work but it doesn't. hyper-transparent-bg@.1.5.2 is working fine. Thanks a lot!!!

**Comment by dfrankland** [comment]
Great! Not a problem. Closing, since this is now resolved 👍
